spring.application.name=urbaniza
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=urbaniza
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.org.mongodb.driver=WARN
logging.level.org.springframework=WARN
logging.level.org.apache.catalina=WARN